const accountId = 123455;
console.log('accountId ==>', accountId);
let accountEmail = 'shubham@salesforce.com';
var accountPassword = '2345';
accountCity = 'Pune';
//accountId = 55555;
accountEmail = 'Shubham@google.com';
accountPassword = '8888';
accountCity = 'Mumbai';
console.log(typeof accountCity);
console.table([accountId, accountEmail, accountPassword, accountCity]);
let myName;
console.log(myName);
